### ISSUE TITLE
The command is `cargo-htmd`

### ISSUE THREAD

**Issue by dbohdan** [letmutex/htmd-cli#1]
This is weird, since the tool doesn't integrate with Cargo. I'd expect the command to be either `htmd` or `htmd-cli`.

**Comment by letmutex** [comment]
Yeah, thanks for reminding, I made a mistake, it has nothing to do with cargo, will remove that cool cargo- prefix later.

**Comment by letmutex** [comment]
Done in the new version https://github.com/letmutex/htmd-cli/releases/tag/v0.2.0
