### ISSUE TITLE
Should read from stdin and write to stdout by default

### ISSUE THREAD

**Issue by dbohdan** [letmutex/htmd-cli#2]
I have just tried htmd-cli. As a *nix user, I expect command-line tools that process text to act as filters by default: to read from standard input and to write to standard output. That htmd-cli doesn't do this is surprising. It is different from related tools like [Pandoc](https://pandoc.org/) and [cmark](https://github.com/commonmark/cmark). As a result, there seems to be no easy way to test bidirectional conversion with `cmark < test.md | cargo-htmd`, for example.

Please make reading from standard input and writing to standard output the default. To be consistent with others, the program should write to standard output even when given a file as input.

It would also be good to interpret the filename `-` as standard input/output. This is a widespread convention.

**Comment by dbohdan** [comment]
IME, usually they either don't, or they concatenate.

**Comment by letmutex** [comment]
Done in v0.3.0, stdin and stdout are the default i/o now.
https://github.com/letmutex/htmd-cli/releases/tag/v0.3.0
